### ISSUE TITLE
[Text] ปรับ Text ที่เป็น Heading

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#13]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/54769527/231188360-fcaab76f-4115-4d3b-bfd8-79f85c9f5611.png">

ส่วนเมนูหน้าแรก ขอปรับ text นิด เป็นตามนี้ค่ะ

- นโยบายประเด็นร้อน
- นโยบายตามประเด็น
- นโยบายตามพรรค
- เปรียบเทียบนโยบายพรรคต่อพรรค *ฝากดูการตัดคำ นโยบาย ให้อยู่บรรทัดเดียวกัน
- เส้นทางการผลักดันนโยบาย

ส่วน นโยบายตามประเด็นต่างๆ ตัดเหลือแค่ **นโยบายตามประเด็น** ให้เหมือนเมนู

<img width="780" alt="image" src="https://user-images.githubusercontent.com/54769527/231189751-16e07608-2824-41dd-8ccd-03f7ea57ae8a.png">

ส่วน ดูนโยบายตามพรรค ตัดเหลือแค่ **นโยบายตามพรรค** ให้เหมือนเมนู

<img width="838" alt="image" src="https://user-images.githubusercontent.com/54769527/231189912-44ccd37f-223f-402a-9c6b-e7c5639f6197.png">

ส่วน Modal ปรับ Headline เป็น **เส้นทางการผลักดันนโยบาย** ให้เหมือนเมนู
<img width="631" alt="image" src="https://user-images.githubusercontent.com/54769527/231190213-1ce952a5-ff58-4c18-9b53-d3daaddf31ae.png">

ส่วนแถบย่อยแต่ละหน้า ปรับคำเป็น **เส้นทางการผลักดันนโยบาย** ให้เหมือนเมนู
<img width="716" alt="image" src="https://user-images.githubusercontent.com/54769527/231190590-c8021d9a-a6e1-4612-a326-aeffe4e5de81.png">

**Comment by petchill** [comment]
All issues are already fixed. Apologized for not open the pull request. All codes are already pushed to main branch and already applied in Staging.
Then, here is smoke test's screen shot from staging.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/31438947/232196174-02c7ed37-d75c-45fc-b126-a1b0aff22f0d.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/31438947/232196190-5f2f50aa-b8a4-4d5b-a7ce-dcb73f68f5d3.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/31438947/232196201-8b7379ce-633d-4462-8387-641c00b4a6a0.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/31438947/232199220-f6e67472-d88c-4527-a957-da56d2d8fb59.png">

<img width="825" alt="image" src="https://user-images.githubusercontent.com/31438947/232196364-689f206b-483f-4e5a-a229-272e3a2d227b.png">
