### ISSUE TITLE
Dropdown เลือกพรรค เรียงตามตัวอักษร ก-ฮ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#14]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/54769527/231194774-9b82254d-834e-4254-b4a9-d1a9c878aefd.png">

**Comment by petchill** [comment]
Already fixed. Here is Screen shot of staging.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/31438947/232200504-43560841-7437-47cd-87aa-aab507eef6e4.png">
