### ISSUE TITLE
[Typo] สระบนซ้อนกันแล้วโดนตัด

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#15]
<img width="233" alt="image" src="https://user-images.githubusercontent.com/54769527/231196192-8b72f49a-c17f-40ec-a7d2-8346e7b7dcda.png">
<img width="248" alt="image" src="https://user-images.githubusercontent.com/54769527/231196251-43bb4ed9-9027-4baa-ae94-475c0f83c481.png">

**Comment by petchill** [comment]
Already fixed. Here is Screen shot in staging.
<img width="801" alt="image" src="https://user-images.githubusercontent.com/31438947/232205790-dd3800b7-9eba-4349-906b-e6baa9509966.png">
