### ISSUE TITLE
[Visual] เปลี่ยนรูปบัตรเป็นสีม่วง

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#17]
Reference [https://www.springnews.co.th/news/election66/837585](url)

**Comment by namsaisup** [comment]
<img width="269" alt="CleanShot 2566-04-17 at 09 50 12@2x" src="https://user-images.githubusercontent.com/123941533/232366304-c1f2bfa7-6b9b-4abc-a14e-38e168cd9981.png">

ทำรูปให้ในfigmaแล้วนะ
+ อย่าลืมเปลี่ยนสีtextจากน้ำเงินเป็นม่วง

**Comment by JaeAiKay** [comment]
@namsaisup บัตรสลับกันหรือป่าวคะ ใบแรกต้องเป็นสีม่วง ใบที่สองสีเขียว

**Comment by napatswift** [comment]
done kub
