### ISSUE TITLE
text คำอธิบายที่เป็นข้อ 1,2,3.. สามารถเคาะบรรทัดเพื่อความอ่านง่ายได้มั้ย (Nice to have)

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#2]
แต่ถ้ามันเป็นการดึงข้อมูลของnocoแบบauto ก็ไม่เป็นไร
![CleanShot 2566-03-27 at 10 22 15@2x](https://user-images.githubusercontent.com/123941533/227835192-8b9a928c-47b4-4780-aeb4-33e681e9808c.png)

**Comment by thanisara-r** [comment]
@naanong-s ใช้ Markdown ได้ ทำไว้ให้ใน NocoDB แล้วค่ะ
