### ISSUE TITLE
[Change Link] view ดูพรรค ส่วน มีนโยบายอะไรมาขายบ้าง ตั้งเป็นลิงก์นี้

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#20]
view ดูพรรค ส่วน มีนโยบายอะไรมาขายบ้าง ฝากตั้งเป็นลิงก์นี้หมดก่อนได้ปะ? (พอดียังไม่เสร็จ แล้วหน้าย่อยไม่ได้มีหน้ารองรับไว้) https://election66.wevis.info/policyshop/

**Comment by napatswift** [comment]
done kub
