### ISSUE TITLE
[Change Text] หน้าเกี่ยวกับโครงการ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#22]
ที่มาของข้อมูล เปลี่ยนเป็น
เอกสารเผยแพร่ศูนย์อำนวยความสะดวกแก่สื่อมวลชน การรับสมัครรับเลือกตั้งสมาชิกสภาผู้แทนราษฎร เป็นการทั่วไป พ.ศ. 2566 
ข้อมูลผู้สมัครรับเลือกตั้ง ส.ส.แบบบัญชีรายชื่อ https://drive.google.com/drive/folders/11S_vXUR27TqM18s1823C8rjnmJhcv-rF
ข้อมูลผู้สมัครรับเลือกตั้ง ส.ส.แบบแบ่งเขตเลือกตั้ง https://drive.google.com/drive/folders/1rI1oheUoQs16odp9LpoZuHHCwGxLKqfZ

**Comment by napatswift** [comment]
sed leaw kub
