### ISSUE TITLE
[Add Text] หน้าเกี่ยวกับโครงการ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#23]
ใช้ text ตามนี้ค่ะ https://bmlpu.notion.site/WeVis-Election-Policy-Shop-58d44b62bf9e47f28ab8a40cc404462e

**Comment by petchill** [comment]
https://staging.election66.wevis.info/policyshop/about

**Comment by thanisara-r** [comment]
ฝากเคาะย่อหน้าส่วนเป้าหมาย (ตาม notion)
และส่วนที่เป็น hyperlink ขอให้เปลี่ยนสี+ขีดเส้นใต้

Ref https://staging.election66.wevis.info/yourcandidates/about

**Comment by MEEP00H** [comment]
https://staging.election66.wevis.info/policyshop/about

ปรับย่อหน้าให้ละครับ

**Comment by petchill** [comment]
เติม underline ให้แล้วครับ
