### ISSUE TITLE
[Change Design] ปรับตำแหน่ง search bar ส่วนนโยบายตามประเด็น

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#24]
ส่วนที่ดูตามประเด็น พอ search bar มันอยู่เหนือหัวข้อ คนนึกว่าให้เสิร์ชจากของที่มีข้างล่าง
ให้ย้ายลงมาด้านล่าง (แบบเลือกพรรค) แล้วเพิ่มคำเป็นว่า ค้นหานโยบายด้วยคีย์เวิร์ดอื่นๆ

![image](https://user-images.githubusercontent.com/54769527/232371289-6ec39002-2ce9-43ec-9e1b-9729bd1abb30.png)

ฝาก @namsaisup ปรับดีไซน์ค่ะ

**Comment by petchill** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/31438947/232646795-127d434c-8214-491b-8d0e-11658ea2c448.png">

**Comment by namsaisup** [comment]
@petchill ฝากเพิ่มคำว่า อื่นๆ ตรงช่องsearch ค่า

![CleanShot 2566-04-18 at 10 04 58@2x](https://user-images.githubusercontent.com/123941533/232660493-61be725f-0d70-46f3-bc83-2139707a61ba.png)
