### ISSUE TITLE
[Add Text] เมื่อค้นคีย์เวิร์ดแล้วไม่เจอนโยบาย

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#26]
![image](https://user-images.githubusercontent.com/54769527/232371697-86ae2a55-aabe-42c2-bdf3-5b75e8430c60.png)

stage ที่ค้นคีย์เวิร์ดแล้วไม่เจอนโยบาย น่าจะต้องมี text ขึ้นนิดนะ เดี๋ยวคนนึกว่าโหลดยังไม่เสร็จ
เสนอคำง่ายๆ อย่าง **ไม่พบนโยบายตามคีย์เวิร์ดที่ค้นหา**

@namsaisup ช่วยสเปคหน่อยค่ะ

**Comment by petchill** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/31438947/232646897-5a663168-b6a1-46c1-b148-09eaad4c092b.png">
