### ISSUE TITLE
[Remove Text] ตัดคำว่า เรียงตาม ออกจากทุกหน้า

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#27]
![image](https://user-images.githubusercontent.com/54769527/232371951-8d8a6975-d74f-4347-9b48-d0d7b078b00f.png)

**Comment by petchill** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/31438947/232636549-69d67d42-69d1-4930-8b25-39e4c81c24d7.png">
