### ISSUE TITLE
[Text] เพิ่มคำว่า "อื่นๆ" ตรงช่องsearchนโยบายตามประเด็น

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#29]
![CleanShot 2566-04-18 at 10 08 33@2x](https://user-images.githubusercontent.com/123941533/232660959-6754aa74-7f43-4161-aca4-ee38645fc5a2.png)

**Comment by petchill** [comment]
![image](https://user-images.githubusercontent.com/31438947/232948040-22d0c4be-2ac0-4807-99d0-c8c90aa7fbfe.png)
