### ISSUE TITLE
[Visual] เพิ่ม icon ประเด็นต่างๆ

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#33]
![CleanShot 2566-04-20 at 00 38 44@2x](https://user-images.githubusercontent.com/123941533/233156030-f4db0364-bde3-4c5c-a5ae-c7182028d2f4.png)

icon แบ่งออกเป็น 3 ขนาด
1. big : สำหรับส่วนประเด็นร้อน
2. medium : สำหรับส่วนประเด็นต่างๆ
3. small : สำหรับอยู่ในการ์ดประเด็น
โดยทุกประเด็นจะมี 2,3 แต่เฉพาะประเด็นร้อนที่มี 1 ด้วย

ไฟล์icon อยู่ในdrive
https://drive.google.com/drive/u/0/folders/1mRIrXNCabHDibnROCBcTi6y2ugT2nXXX

**Comment by petchill** [comment]
![image](https://user-images.githubusercontent.com/31438947/233250384-5b4d13ad-46c5-45db-8462-feedd8457281.png)

![Uploading image.png…]()
