### ISSUE TITLE
[Remove Visual+Link] เอาเครื่องหมายถูก+ลิงก์ 3 อัน ออกจากพรรคการเมืองที่ไม่ได้อยู่ในสภา 62

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#35]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/54769527/233532031-3a23a2c5-89d8-45eb-9a8b-0c3063fa74f8.png">

**Comment by MEEP00H** [comment]
<img width="791" alt="Screenshot 2023-04-23 at 12 58 57" src="https://user-images.githubusercontent.com/25168807/233822498-d3b7e4fe-aea8-420a-b93a-241193202cdb.png">
