### ISSUE TITLE
[Interaction] หน้าเปรียบเทียบนโยบาย ตรงช่องเลือกพรรค ควรเสิร์ชชื่อพรรคได้

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#36]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/54769527/233534137-0f59ae01-10b9-4a04-9963-68035a28107b.png">

**Comment by thanisara-r** [comment]
+ ตรง dropdown ลิสต์ ฝากช่วยเรียงตามตัวอักษรด้วยจ้า

**Comment by petchill** [comment]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/31438947/234050822-a18c7eb8-19fd-4b96-a0f8-237699e145de.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/31438947/234050891-faee6497-819d-4a34-bd45-c49604d97b9e.png">
