### ISSUE TITLE
[Visual] ปรับขนาดและตำแหน่งกล่องข้อความ

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#38]
![CleanShot 2566-04-21 at 10 25 01](https://user-images.githubusercontent.com/123941533/233533788-88a04480-de80-4140-a4d8-bc6132130d7f.png)

**Expectation :**
![CleanShot 2566-04-21 at 10 31 38@2x](https://user-images.githubusercontent.com/123941533/233534611-56cf0e32-dca5-4df4-b1ac-c92bac573325.png)
- กล่องอยู่ตรงกลาง
- ความกว้าง 85% ของแถบ นโยบายประเด็นร้อน

**Comment by MEEP00H** [comment]
<img width="791" alt="Screenshot 2023-04-23 at 13 17 28" src="https://user-images.githubusercontent.com/25168807/233823265-c5736c27-8a10-4d2e-a22e-b5e8887ae852.png">
