### ISSUE TITLE
[Add Text] หน้าเปรียบเทียบนโยบาย ถ้าพรรคที่เลือกไม่มีนโยบายประเด็นนั้น แสดง text ว่าไม่มี

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#39]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/54769527/233534570-ef00f4f5-f76b-4da9-8aca-c76832a4224f.png">

@namsaisup ฝากวาง text **ไม่มีนโยบายประเด็นนี้**

**Comment by namsaisup** [comment]
<img width="457" alt="CleanShot 2566-04-22 at 06 08 39@2x" src="https://user-images.githubusercontent.com/123941533/233747109-6c7430a7-938b-4b5c-9a05-bd62a46e747d.png">

ขนาดtext B4

**Comment by MEEP00H** [comment]
<img width="834" alt="Screenshot 2023-04-23 at 13 53 45" src="https://user-images.githubusercontent.com/25168807/233824704-49394f20-a964-4e38-af08-c693361bc902.png">
<img width="859" alt="Screenshot 2023-04-23 at 13 53 58" src="https://user-images.githubusercontent.com/25168807/233824707-3916d5c6-13f3-4ee6-9cd5-be36f87e1d91.png">
