### ISSUE TITLE
[Content] คำอธิบายไม่ค่อยเข้าใจว่าพรบ.สุราก้าวหน้า เอาไว้ทำอะไร

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#4]
![CleanShot 2566-03-27 at 10 23 35@2x](https://user-images.githubusercontent.com/123941533/227835548-abb491cc-ae8e-41be-865c-dee23718db5a.png)

**Comment by thanisara-r** [comment]
ปรับคำอธิบายใหม่แล้ว ฝาก @naanong-s ดึงจาก NocoDB ใหม่ค่ะ
