### ISSUE TITLE
[Visual] เพิ่มความหนาเส้นกรอบเป็น 2px

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#40]
![CleanShot 2566-04-21 at 10 34 45](https://user-images.githubusercontent.com/123941533/233534928-f853fe87-8e60-43e8-b26a-5ac6ee74d9ff.png)

**Expectation**
<img width="299" alt="CleanShot 2566-04-21 at 10 36 20@2x" src="https://user-images.githubusercontent.com/123941533/233535119-40dd7d54-59c7-40e2-9adf-cc77fa00dd61.png">

**Comment by petchill** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/31438947/234051020-18098e46-25d1-42f2-900b-d0752a612868.png">
