### ISSUE TITLE
feat(/party/) เพิ่มรายชื่อแคนดิเดตนายก

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#42]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/54769527/233535196-f37b4bcc-7b8d-4ddb-b43a-bf71b0095f7f.png">

https://docs.google.com/spreadsheets/d/1ooBHq0DWCbpH2KhHRmC2kwn4nV6gQO40PEYlDL8woCY/edit#gid=1031775852

กรณีพรรคนั้นไม่มีแคนดิเดตนายก ให้ใส่คำว่า **ไม่มีแคนดิเดตนายก**

**Comment by MEEP00H** [comment]
<img width="786" alt="Screenshot 2023-04-23 at 12 03 55" src="https://user-images.githubusercontent.com/25168807/233820859-379ea15d-64e5-434a-858a-c4f72926381b.png">
<img width="799" alt="Screenshot 2023-04-23 at 12 04 00" src="https://user-images.githubusercontent.com/25168807/233820871-506b11ae-661a-489c-8ce1-c4544fde2b96.png">

เพิ่มแล้วครับ
