### ISSUE TITLE
feat: add simulation error remark

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/thailand-election-2023#43]
Election sim เราเอาคะแนน  350 เขตมาแจกแจงเป็นรายตำบล แล้วรวมรายตำบลมาเป็น 400 เขตตามข้อมูลปีล่าสุด สื่งที่พบคือ

- มันมี บางตำบลที่ข้อมูล 350-400 ไม่ตรงกันที่ผมยังไม่สามารถ manual check ได้ว่าข้อมูลตรงหล่นหรือพิมไม่ตรงกัน
- นอกจากนี้ 400 ของปีนี้เหมือนจะมีข้อยกเว้นระดับเทศบาลทำให้คะแนนบางตำบลเบิ้ลไปอีก
- คะแนนรวม 350 เขต (ุ62) = 35,596,433 และ 400 เขต (ุ66) = 36,169,916

ถ้ามีเวลาผมอาจจะกลับมา recheck อีกที แต่อยากให้ใส่ remark ไว้นิดนึงเพราะน่าจะทำให้ครงเป๊ะยาก

**Comment by taepras** [comment]
done https://github.com/wevisdemo/thailand-election-2023/commit/eb88216361d1cec6d74aa3daa50dc787cd677064
