### ISSUE TITLE
Party Sorting in Election Zone  Page

### ISSUE THREAD

**Issue by p16i** [wevisdemo/thailand-election-2023#44]
Hi, 

Thank you for developing the tool!  I personally enjoy using it every much.

But, one thing that is unclear to me is the sorting of parties in each election zone.

Would you mind elaborating a bit how is the sorting key here?

![image](https://user-images.githubusercontent.com/1214890/233723877-ccbed5e8-f5b8-431a-9cb7-8f5b6d723c05.png)

_Source_: https://election66.wevis.info/yourcandidates/เชียงใหม่/1/

**Comment by Th1nkK1D** [comment]
Hi, thank you for the feedback!

@napatswift @JaeAiKay can you help check this?

**Comment by napatswift** [comment]
Hi, thank you for your feedback! I'm glad you're enjoying the tool.

I've updated the code to sort the list by party number. This should fix the issue you're experiencing. 

Please let me know if you have any other questions. 😀
