### ISSUE TITLE
bug: แก้คำตอบแล้วฝ่ายที่เราเลือกไว้ตอนลองจัดตั้งรัฐบาลหายไป

### ISSUE THREAD

**Issue by taepras** [wevisdemo/thailand-election-2023#45]
bug report คร้าบ

**Scenario**
- เล่น Quiz จบ 1 รอบ
- ลองกดจัดตั้งรัฐบาล แล้วมีการสลับพรรคฝ่ายค้าน/รัฐบาล
- กดกลับไปแก้คำตอบ เพื่อดูผลใหม่ถ้ามีการเปลี่ยนแปลงคำตอบบางอย่าง
- กดกลับมาที่หน้า result

**สิ่งที่เกิดขึ้น**
- ฝ่ายที่เรา assign ไว้หายไป ต้อง assign ใหม่

**สิ่งที่อยากให้เป็น**
- ฝ่ายที่เรา assign ไว้ ยังอยู่

**Comment by Th1nkK1D** [comment]
@tesol2y090 ในเคสนี้คงต้องแก้ opposition ใน party store ไปเลย หรือไม่ก็สร้าง store เพิ่มสำหรับเก็บฝ่ายที่ custom โดยเฉพาะ คิดว่าอันไหนก็ได้นะ แต่บอกด้วย55555

**Comment by tesol2y090** [comment]
> 

ถ้าแก้ที่ party store ไปเลยจะกระทบอะไรไหมครับผมพวกคะแนนหรือแผนที่

**Comment by Th1nkK1D** [comment]
@tesol2y090 กระทบตอนคำนวนนิดหน่อย แต่เราแก้ได้ง่ายมาก ถ้าจะไปทางนี้เดะพน.ปรับตาม

**Comment by tesol2y090** [comment]
เวลามาหน้า result (หน้าจำลองผล) ทุกครั้งมันจะ load data ใหม่ทุกครั้งอะครับ เราเปลี่ยนตอน load data เป็นที่หน้า home (หน้าแรก) เลยได้ไหมนะครับ

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D เวลามาหน้า result (หน้าจำลองผล) ทุกครั้งมันจะ load data ใหม่ทุกครั้งอะครับ เราเปลี่ยนตอน load data เป็นที่หน้า home (หน้าแรก) เลยได้ไหมนะครับ

สาเหตุที่เราไม่ได้ load data ที่หน้าแรกเพราะ

1. เราอยาก lazy-load ให้ได้มากที่สุด ประมาณว่าถ้ายังไม่ใช้ก็ไม่ต้องโหลด ถ้าเกิดเขาเล่น quiz ไม่จบแล้วออกก็โหลดมาฟรี + ถ้าน่าแรกโหลดนานมันไม่น่าเล่น
2. browser มี cache อยู่ ต่อให้เราเรียก code ที่ไป fetch data ซ้ำ ถ้าเป็นไฟล์ที่เพิ่งโหลดไป มันไม่เสียเวลา download data ใหม่ (อันนี้ตามความเข้าใจเรา กำลังคิดเหมือนกันว่าจะ validate idea นี้ยังไงดีนะ)
3. จากที่ลองเล่นอะ ตอนนี้ส่วนที่นานที่สุดของหน้า result ไม่ใช่ data แต่เป็นการคำนวน งานนี้ data ไม่ได้ใหญ่มากเมื่อเทียบกับงานอื่น

คิดว่าสมเหตุสมผลไหมนะ

**Comment by tesol2y090** [comment]
> > @Th1nkK1D เวลามาหน้า result (หน้าจำลองผล) ทุกครั้งมันจะ load data ใหม่ทุกครั้งอะครับ เราเปลี่ยนตอน load data เป็นที่หน้า home (หน้าแรก) เลยได้ไหมนะครับ
> 
> สาเหตุที่เราไม่ได้ load data ที่หน้าแรกเพราะ
> 
> 1. เราอยาก lazy-load ให้ได้มากที่สุด ประมาณว่าถ้ายังไม่ใช้ก็ไม่ต้องโหลด ถ้าเกิดเขาเล่น quiz ไม่จบแล้วออกก็โหลดมาฟรี + ถ้าน่าแรกโหลดนานมันไม่น่าเล่น
> 2. browser มี cache อยู่ ต่อให้เราเรียก code ที่ไป fetch data ซ้ำ ถ้าเป็นไฟล์ที่เพิ่งโหลดไป มันไม่เสียเวลา download data ใหม่ (อันนี้ตามความเข้าใจเรา กำลังคิดเหมือนกันว่าจะ validate idea นี้ยังไงดีนะ)
> 3. จากที่ลองเล่นอะ ตอนนี้ส่วนที่นานที่สุดของหน้า result ไม่ใช่ data แต่เป็นการคำนวน งานนี้ data ไม่ได้ใหญ่มากเมื่อเทียบกับงานอื่น
> 
> คิดว่าสมเหตุสมผลไหมนะ

ดีเลยครับ ผมไม่ได้คิดส่วนนี้เลย งั้นเดี๋ยวผมลอง handle ดูเวลา load data ใหม่อีกรอบถ้ามี data เดิมอยู่แล้ว แล้วก็ไม่ต้อง load ใหม่ ดีกว่า ไม่น่าติดอะไรเนอะครับผม

**Comment by tesol2y090** [comment]
@Th1nkK1D ตัวที่ทำให้ party กลับไปเป็น initial PartyGroup คือ 

```ts
await party.load();
```

อันนี้อันเดี๋ยวป่ะครับ ถ้าเคยโหลด data นี้แล้ว disable รอบใหม่ก็เพียงพอเนอะครับ

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D ตัวที่ทำให้ party กลับไปเป็น initial PartyGroup คือ
> 
> https://github.com/wevisdemo/thailand-election-2023/blob/main/apps/electionsim/src/routes/result/%2Bpage.svelte#L38
> 
> อันนี้อันเดี๋ยวป่ะครับ ถ้าเคยโหลด data นี้แล้ว disable รอบใหม่ก็เพียงพอเนอะครับ

ใช่ๆ น่าจะมีแค่อันนี้อันเดียว

**Comment by tesol2y090** [comment]
Fix in this commit krub.
https://github.com/wevisdemo/thailand-election-2023/commit/4d70ebe358839169fbbd3ec4c217296cc3166d55
