### ISSUE TITLE
request: ถ้าคำนวณเสร็จแล้วพรรคฝ่ายค้านมีมากกว่าพรรครัฐบาล ให้สลับฝั่งให้เลย ไม่ต้องกดสลับเอง

### ISSUE THREAD

**Issue by taepras** [wevisdemo/thailand-election-2023#46]

**Comment by tesol2y090** [comment]
Fix in this commit krub. https://github.com/wevisdemo/thailand-election-2023/commit/0d350729b6610e496198e97e974d9475cf322865
