### ISSUE TITLE
[Data] ตัวเลือกพรรค มีพรรคที่ไม่ได้ลงเลือกตั้ง 66 อยู่ด้วย

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#47]
ดูรายชื่อ 70 พรรค ได้ที่นี่ค่ะ https://docs.google.com/spreadsheets/d/10UW2OhYaEYWdKfIfi7QwmfOfkVlr2PCK19-ffkJB2Is/edit#gid=922087840

**Comment by petchill** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/31438947/234050467-22422f13-dc5a-47ae-8d20-a74d6e9ac42f.png">
ตอนนี้ผม filter เอาตาม field isActive ใน nocodb นะครับ

**Comment by MEEP00H** [comment]
isActive จะมีแค่ 24 พรรคนะ
