### ISSUE TITLE
request: ถ้ามีการ refresh จากหน้า quiz/result/share แล้วข้อมูลไม่ valid แล้ว อยากให้ redirect กลับไปที่ home ด้วยครับ

### ISSUE THREAD

**Issue by taepras** [wevisdemo/thailand-election-2023#48]
ไม่งั้น state มันจะดูค้างๆ

**Comment by tesol2y090** [comment]
ข้อมูลไม่ valid นี้มี criteria ไม่ครับหรือแค่ refresh แล้วเด้งกลับเลย

**Comment by tesol2y090** [comment]
Fix refresh in this commit krub.
https://github.com/wevisdemo/thailand-election-2023/commit/5e781622aed2cdf9574788e1aa9d44d67ddcce9e

**Comment by Th1nkK1D** [comment]
> Fix refresh in this commit krub. [5e78162](https://github.com/wevisdemo/thailand-election-2023/commit/5e781622aed2cdf9574788e1aa9d44d67ddcce9e)

เท่าที่ลองใน staging มันไม่ถูกนะ เพราะเรา force ไป `/` แต่หน้าหลักของ project นี้ (base path) อยู่ที่ `/electionsim` ให้เปลี่ยนไปใช้ตัวแปร base ของ svelte ที่จะเก็บ baspath ที่ถูกต้องไว้ 

```js
import { base } from '$app/paths';
import { goto } from '$app/navigation';

if (!$contentManager.isQuizing) {
  goto(base);
}
```

**Comment by taepras** [comment]
เจอบั๊กครับ ถ้า refresh จากหน้า result แล้วจะเป็นหน้าขาวๆ เหมือน page ที่เหลือโดนผลักไปด้านล่างหมด @tesol2y090 
![image](https://user-images.githubusercontent.com/6916654/234337670-b926ce6c-3be5-4b10-8400-cf4311a6c0b1.png)

**Comment by tesol2y090** [comment]
Fix in this commit krub.
https://github.com/wevisdemo/thailand-election-2023/commit/753e4ae1e640e702dee18cb6c0f9581e0bc4f03d
