### ISSUE TITLE
(/policyshop/party/ชื่อพรรค) เลือกดูนโยบายเฉพาะประเด็นในหน้ารวมนโยบายแต่ละพรรคแล้วข้อมูลไม่เปลี่ยนตามประเด็นที่เลือก

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#51]
https://user-images.githubusercontent.com/54769527/234187617-71d2ca8b-4d63-477c-a196-dd489f53130b.mov

**Comment by MEEP00H** [comment]
![Uploading Screenshot 2023-04-25 at 13.44.26.png…]()

**Comment by thanisara-r** [comment]
ขออภัย อาจจะอธิบายไม่ชัด
- ถ้ายังไม่เลือกประเด็น > เห็นนโยบายทั้งหมด
- ถ้าเลือกประเด็นแล้ว > เห็นนโยบายเฉพาะในประเด็นที่เลือก
