### ISSUE TITLE
feat (/electionsim/result) ลูกศรขึ้นลงหน้าสรุปผล แสดงผิด

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#53]
ลูกศรขึ้นลง ที่เปรียบเทียบการเพิ่ม-ลดจากจากปี 62 ยังแสดงผลผิดค่ะ
ตัวอย่าง เล่นแล้ว ก้าวไกลได้ 40 ที่นั่งในปี 66 
แต่ปี 62 ก้าวไกลได้ 81 ที่นั่ง
ควรเป็นลูกศรลง (ลดลง)

![image](https://user-images.githubusercontent.com/54769527/234242920-06a8b06d-52ed-417e-b9a4-8eb4e2613913.png)

![image](https://user-images.githubusercontent.com/54769527/234243227-b76a3f7f-78fa-43a7-9ff2-60cc87ebd0d0.png)

**Comment by tesol2y090** [comment]
Fix in this commit krub.
https://github.com/wevisdemo/thailand-election-2023/commit/b275a369233208c96e427ead93df596577e0aa7b
