### ISSUE TITLE
[Visual] รูปนี้ไม่ค่อยชัด

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#55]
![image](https://user-images.githubusercontent.com/54769527/234259898-e6e4afb0-b6a1-47f7-b45f-d2d76ebb5009.png)

ไม่แน่ใจเป็นที่ไฟล์ต้นทางหรือยังไง? + logo ภูมิใจไทย หายไปอันนึง @taepras

**Comment by Th1nkK1D** [comment]
อันนี้ผมคุยกับ @taepras แล้วครับ รูปนี้ยังเป็นข้อมูล mock เดี๋ยวผมทำข้อมูล final ให้เต้ไปทำรูปใหม่ครับ

**Comment by Th1nkK1D** [comment]
@taepras simulation result using district popularity for partylist without any parameters and randomness 

![image](https://user-images.githubusercontent.com/8860448/234300152-d670548d-a479-4407-9391-90c20a0d8efe.png)

ฝากทำรูปต่อครับ

**Comment by taepras** [comment]
fixed
https://github.com/wevisdemo/thailand-election-2023/commit/756a49577f030242cb5ff9a87f13fe1f6f0a576a
