### ISSUE TITLE
bug: เวลากดปิดหน้า edit quiz แล้ว loading เด้งไปอยู่ข้างล่าง

### ISSUE THREAD

**Issue by taepras** [wevisdemo/thailand-election-2023#58]
ต้อง scroll ลงไปถึงจะเจอว่ามี loading ค้างอยู่
https://photos.app.goo.gl/sJPPoHXQyv25rJgy6

**Comment by tesol2y090** [comment]
Fix in this commit krub.
https://github.com/wevisdemo/thailand-election-2023/commit/7ada4b929bad941a2270ee9da63909b4fe5e64d5
