### ISSUE TITLE
bug: chart ส่วนจัดตั้งรัฐบาลแสดงไม่ถูกต้อง

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/thailand-election-2023#59]
![image](https://user-images.githubusercontent.com/8860448/234586249-41387751-6b1a-4f60-9a78-8186c1efad32.png)

เจอ 2 ปัญหาตรง chart จัดตั้งรัฐบาลคือ
1. บางพรรคข้อมูลที่ hover ไม่ตรงกับ chart (จาดรูป hover ภูมิใจไทย แต่โชว์ว่าเป็นชาตืไทยพัฒนา)
2. แถบ stripe ที่ hightlight ไม่ถูก ฝ่ายค้านมีเยอะกว่านั้นถ้าดูจากรายชื่อด้านล่าง

อันนี้คือ preset ที่ทำให้เจอผลลัพข้างบน

![image](https://user-images.githubusercontent.com/8860448/234587369-9e59a72a-343f-4e0e-b4a9-07a407659641.png)

**Comment by tesol2y090** [comment]
Fix in this commit krub.
https://github.com/wevisdemo/thailand-election-2023/commit/dbacbcbfbbd205618bb8f1240d5e445333bb0980

**Comment by Th1nkK1D** [comment]
> Fix in this commit krub. [dbacbcb](https://github.com/wevisdemo/thailand-election-2023/commit/dbacbcbfbbd205618bb8f1240d5e445333bb0980)

เท่าที่ลองเช็ค ตัว tooltip ถูกละ แต่ว่าปํญหาแถบแรเงายังอยู่นะ ตัวแรเงามันควรจะคลุมฝ่ายค้ายทั้งหมด แต่จากรูปมันคลุมไม่ครบ ภูมืใจไทยกับประชาธิบัตรต้องอยู่ใต้แรเงาด้วยเพราะเป็นพรรคฝ่ายค้าน

![image](https://user-images.githubusercontent.com/8860448/234705532-a3b92c68-e2e8-4b3f-bd22-edc43b05db06.png)

**Comment by tesol2y090** [comment]
อันนี้ตอบ set แบบด้านบนเลยป่ะครับ ของผมได้นะ แต่ที่สังเกตุคือคะแนนฝ่ายค้านไม่ตรงจริง

**Comment by tesol2y090** [comment]
Maybe this commit work krub.
https://github.com/wevisdemo/thailand-election-2023/commit/5e269ee4009a996f5cddfc923dc3bed75bd01609

**Comment by Th1nkK1D** [comment]
> Maybe this commit work krub. [5e269ee](https://github.com/wevisdemo/thailand-election-2023/commit/5e269ee4009a996f5cddfc923dc3bed75bd01609)

แปลกกก เพราะเราใช้ vivaldi browsert เหรอ แต่ render engine มันควรจะเหมือน chrome แต่ถ้าจากที่แก้มามันไม่ได้นะ

1. async await ตรงนั้นไม่มีผลอะไร เพราะมันอยู่ใน onMount และไม่มี function ทำงานต่อ
2. `districtPopularity.calculate()` อยู่หลัง `await partylistPopularity.load()` ไม่ได้เพราะตอนนี้มี option ที่ลือกไม่ใช้ poll แล้วเอาผลจากคะแนนเขตมาใช้กับ partylist

เดี๋ยวเราลองดูต่อให้ละกัน เพราะว่ามันพังที่เครื่องเรา น่าจะไล่ง่ายกว่า
