### ISSUE TITLE
[Visual] เพิ่ม Loading state

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#60]
ไฟล์ Lottie
https://drive.google.com/file/d/1qnV8oIoRfAYV2DkZaFHTd_QottjwCmjS/view?usp=sharing

**Comment by petchill** [comment]
ไม่สามารถทำได้ซะทีเดียวครับเนื่องจาก project ไม่มีการ load ข้อมูลจาก network จะ load ตอน build time ที่ขึ้น blank stage อาจเพราะว่า component มีมากเกินจน browser load ไม่ทัน ที่แก้ได้เบื้องต้นคือ จับ event ว่า component render เสร็จเมื่อไหร่ ให้เอา loading ออก แต่ก็ไม่สามารถเชื่อได้ 100% เพราะการ load component เป็นแบบ paralel กัน ไม่รู้ว่าอะไรจะเสร็จก่อน
