### ISSUE TITLE
[Visual] หน้า viz ขนาดไม่ตรงกับในดีไชน์

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#61]
![Screen Shot 2023-05-02 at 14 13 23](https://user-images.githubusercontent.com/132336578/235603875-83ad27b0-aad2-4aff-9173-b97eba8a8300.png)

มันแหกออกมาเต็มจอใหญ่เกิน
Device: Macbook pro 13'
Browser: Chrome

**Comment by thanisara-r** [comment]
Overview Chart ซ้ายมือ ตอนนี้ดูไม่ออกเลยอะว่าเป็นชาร์ต ไม่แน่ใจปรับ scale ได้ไหม?

**Comment by Bariyard** [comment]
แก้ไข sizing ให้นิดนึงแล้วครับ

**Comment by Bariyard** [comment]
@monsichasri
