### ISSUE TITLE
[Interaction] กดปุ่ม shuffle แล้ว ไปหน้าไม่พบสิ่งที่ค้นหา

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#62]
ควรกดแล้วสุ่มคนออกมาให้เลย ไม่ได้สุ่ม filter ให้ เพราะบาง filter สุ่มมาแล้วไม่เจออะไรเลยอาจจะงงได้

**Comment by Bariyard** [comment]
done ka
