### ISSUE TITLE
[Filter] การเรียงลำดับใน "ค้นหาหมวดธุรกิจ"

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#63]
![Screen Shot 2023-05-02 at 14 42 00](https://user-images.githubusercontent.com/132336578/235608315-f24f51c0-31ff-4b4c-bce7-e215d4eb8f55.png)

อยากให้เรียงจากมากไปน้อย โดยทุกหมวดธุรกิจอยู่บนสุด

**Comment by Bariyard** [comment]
done ka please recheck

**Comment by Bariyard** [comment]
done ka @monsichasri
