### ISSUE TITLE
[Filter] สีพรรคใน "ค้นหาพรรคการเมือง"

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#64]
![Screen Shot 2023-05-02 at 14 44 21](https://user-images.githubusercontent.com/132336578/235608714-7b0e7d90-eb35-4091-bdcd-e58b0ffc212d.png)

ยังมีแค่สีเทากับแดง ยังไม่เป็นสีจริง

**Comment by Bariyard** [comment]
อันนี้ ตาม design คือ

เทา = Inactive
แดง = Active มั้ยครับ

**Comment by monsichasri** [comment]
เทา = Inactive
สีตามพรรค = Active (เหมือนที่โชว์ในชาร์ต)

ในดีไซน์เป็น mockup เลยทำสีเดียวกันหมด โทษทีค่า

**Comment by Bariyard** [comment]
done ka please re-check
