### ISSUE TITLE
[Visual] เอารูปออก list หุ้นส่วนที่ไม่ใช่คน 

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#66]
![Screen Shot 2023-05-02 at 14 48 32](https://user-images.githubusercontent.com/132336578/235624100-432183fe-666a-4bb9-87d4-8e72c2a0a7ee.png)

พวกที่เป็นกองทุนใดๆ ขอเป็นลิสต์เฉยๆ แบบไม่มีรูปไปเลย

**Comment by monsichasri** [comment]
งั้นเอาไว้ก่อนก็ได้ค่ะ เป็น nice to have🥲 แค่กลัวคนงง พอมันขึ้นเป็นบริษัทกับกองทุนแต่เป็นรูปหน้าคน

**Comment by Bariyard** [comment]
not fixed ka fixed yak @monsichasri
