### ISSUE TITLE
[Interaction] ยังคนจากบริษัทเชื่อมไปไม่ได้

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#67]
![Screen Shot 2023-05-02 at 16 08 20](https://user-images.githubusercontent.com/132336578/235626402-f0d7af25-63bc-41ae-b557-28eb7753bcbe.png)

กดมาจากคนที่เป็นนักการเมือง > ไปบริษัท > แต่ยังกดจากคนกลับไปไม่ได้

**Comment by Bariyard** [comment]
กดคนกลับไม่ได้ครับ เพราะไม่ได้มีข้อมูลทุกคน T T บางคนไม่เกี่ยวกับการเมืองครับ Y Y

**Comment by monsichasri** [comment]
คนแค่กดที่เกี่ยวก็ไม่ได้ใช่มั้ยงะ
