### ISSUE TITLE
[Interaction] Lock scroll เมื่อถึงหน้า viz

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#68]
อยากให้ lock หน้า viz ไว้ไม่ให้เลื่อนไปได้เมื่อมาถึงหน้านี้
- ถ้าจะกลับขึ้นบน ให้ใช้ ปุ่ม ? มีกลับไปด้านบนอยู่ในนั้น
- ถ้าจะลงล่าง ให้ใช้ ปุ่มแชร์ เพราะข้างล่างไม่มีอะไรนอกจากแชร์
ปุ่มอยู่มุมขวาล่างตามใน figma เลย

![Screen Shot 2023-05-02 at 16 15 31](https://user-images.githubusercontent.com/132336578/235628099-9c7a8da6-58c5-4836-b49b-48fd6da62c95.png)

**Comment by Bariyard** [comment]
เพิ่มไว้ใน chart หลัก fix bottom right ไว้ครับ
แต่ ในหน้า chart อื่นๆ หลังจากเลือก person หรือ business ไปแล้ว 
จะไม่โชว์นะครับ เพราะมันจะมีการทำ step tutorial ซึ่งควรเริ่มที่หน้าหลักเสมอ

**Comment by monsichasri** [comment]
งั้นหน้า Chart อื่นๆ ขอแค่ปุ่มแชร์ได้มั้ยคะ
คือเลื่อนขึ้นได้แต่เลื่อนลงต่อไม่ได้แล้ว
เพราะพอมันเลื่อนลงได้แล้วเจอหน้าโล่งทั้งหน้ามีแชร์นิดเดียวอาจจะดูแปลกๆ

**Comment by thanisara-r** [comment]
สรุปแก้ปัญหาด้วย
1. ยก session แชร์ + เกี่ยวกับโครงการ มาอยู่ก่อน viz
2. เพิ่ม ui (ลูกศร) ให้ user รู้ว่า scroll ต่อได้
3. stick footer ไปกับ viz
