### ISSUE TITLE
[Visual-Mobile] แถบด้านล่างหาย แถบด้านบนถูกตัด

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#69]
![IMG_1966](https://user-images.githubusercontent.com/132336578/235631867-d67e48e9-2f3c-48a4-ab8b-341f2e5ef5f3.PNG)

แถบด้านล่างเมื่อเลื่อนถึงจะเจอ ซึ่งจริงๆควรมีอยู่แล้ว
Device: iphone 13 mini
Browser: safari

**Comment by rootEnginear** [comment]
fixed with 1abab3513a4a4bbbc97cb17667c06db86d577fa1
