### ISSUE TITLE
[Visual-Mobile] icon ต่ำสุดสีผิด

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#70]
![IMG_1965 copy](https://user-images.githubusercontent.com/132336578/235632694-f5ad7bfe-02af-451e-8c23-967d2eb6f101.PNG)
มีสีขาวแปลกๆติดมาขีดเล็กตามรูป จริงๆควรเป็นสีดำ

**Comment by Bariyard** [comment]
done ka

**Comment by Bariyard** [comment]
done ka @monsichasri
