### ISSUE TITLE
[Interaction-Mobile] กดบางคนจาก chart แล้วขึ้น error

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#71]
![IMG_1964](https://user-images.githubusercontent.com/132336578/235632952-2bf7ba52-66af-4aa6-89e1-cc7c01c0ddc3.PNG)
เข้ามาแล้วลองเลือกกดคนแรก(พิบูลย์ รัชกิจประการ) แล้วขึ้นแบบนี้เลย ไม่ได้กดไปไหนมาก่อน
แต่ลองเลื่อนๆไป ก็กดไปคนอื่นได้อยู่

Device: iphone 13 mini
Browser: Safari

**Comment by Bariyard** [comment]
done ka เป็นที่ ฟังชั่น regex เอาออกและใช้วิทีอิ่นแล้ว
