### ISSUE TITLE
[Viz-mobile] ไม่ขึ้นเส้น connection ของใครเลย

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#72]
ลองสุ่มๆ กดไปกี่คนก็ไม่ขึ้นเส้นที่เชื่อมบริษัท ขึ้นรูปหน้าเฉยๆ

Device: iphone 13 mini
Browser: Safari

**Comment by Bariyard** [comment]
done krub ตอนนี้ได้แล้วครับ
