### ISSUE TITLE
[Text] เปลี่ยนคำว่า Politics & Business เป็น MP Asset

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#73]
<img width="883" alt="image" src="https://user-images.githubusercontent.com/54769527/235648751-7c6aa370-1604-4d70-a7e9-b0e3679e4c91.png">

**Comment by Bariyard** [comment]
@monsichasri รบกวนแก้ OG ด้วยครับ

**Comment by monsichasri** [comment]
OG ค่า https://drive.google.com/drive/folders/1uPjIwSeqCGDJjYt7kLE01NkZ0sqchDGp
UI ที่แก้คือหมายถึงพี่บาสแค่พิมพ์ใหม่ในเว็บเนอะ เราต้องทำอะไรปะ
*เพิ่มเติม ในเว็บหลัก election66 ที่ link มา น่าจะต้องแก้คำด้วย
