### ISSUE TITLE
[Text] แก้คำ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#74]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/54769527/235648984-b3d2411c-719c-44cc-91c9-800c64d78cb5.png">

จาก "ทั้งผู้สมัคร ส.ส. , ส.ส. และ ครม.ใครกัน.."

เป็น "ทั้งผู้สมัคร ส.ส. เลือกตั้ง 66 รวมถึง อดีต ส.ส. และ ครม. จากเลือกตั้ง 62 ใครกัน.."

**Comment by Bariyard** [comment]
done ka
