### ISSUE TITLE
[Data] เจอเคสแสดงข้อมูลว่าเป็นผู้ถือหุ้น แต่สัดส่วนหุ้น 0%

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#75]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/54769527/235666753-a1a0f3d9-6e17-411e-80a9-e6b2523510e3.png">

ไม่แน่ใจหมายความว่ายังไง แต่ถ้าดูจะเข้าใจว่าไม่มีหุ้นอยู่ คำถามคือ
1. แล้วทำไมถึงมีชื่อบริษัทนี้ในลิสต์บริษัทที่ถือหุ้น ทั้งที่ไม่มีสัดส่วนหุ้น
2. มูลค่ารวมที่คำนวณ คิดรวมมูลค่าบริษัทที่ไม่มีสัดส่วนหุ้นด้วยไหม

ฝากรีเช็คหน่อยค่ะ

**Comment by Bariyard** [comment]
พอดีว่าเอา percentage มาทำ format 2 decimal point ครับ

ค่าจริงอยู่ที่
"company_name_th":"พีดี เขาใหญ่ จำกัด","pct_share":0.0001,
"company_name_th":"พีดี โคราช จำกัด","pct_share":0.0001

เลขนี่ส่งมาจาก creden
ให้โชว์ค่าจริงเลยดีมั้ยครับ

**Comment by thanisara-r** [comment]
ให้แสดงเป็น **< 0.01%** ได้เลยค่า

**Comment by Bariyard** [comment]
อันนี้เจอเพิ่มเติมครับ ว่า compare number
ตัวอย่างเช่น 0.0001 < 0 javascript มันมึนมากครับ
ตอนนี้เลยใช้ตัวเลขจริงจาก creden ไปเลย

@thanisara-r ถ้าไม่โอเคเด่วหาวิทีเพิ่มเติมครับ

**Comment by thanisara-r** [comment]
0.0001 < 0 = False
0.0001 < 0 = True
