### ISSUE TITLE
[Visual] รูปคน มีในหน้า Person View แต่ไม่ขึ้นในหน้า Company View

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#76]
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/54769527/235650306-9f32d46c-c13f-4ab6-a0c4-cf5d9b313464.png">

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/54769527/235650411-887679f7-6ed2-4740-b9fb-75a52ca1ecec.png">

**Comment by Bariyard** [comment]
done ka
