### ISSUE TITLE
[Bug] Error Display in Safari

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#77]
เปิดแวบแรก เว็บค้างๆ โหลดนานมาก

พอกดยอมรับ cookies แล้ว ถ้าเปลี่ยนหน้า ข้อมูลจะไม่เหมือนรอบแรกอะ (เปิดรอบแรก มีอุ๊งอิ๊ง เปิดแบบยอมรับ cookies จะเป็นเวอร์ชั่นไม่มี)

https://wevisdemo.slack.com/files/U02MQPG955K/F056J4DSPPS/screen_recording_2566-05-02_at_6.23.10_pm.mov

**Comment by Bariyard** [comment]
แก้โหลดนานแล้วครับ optimize ดีขึ้นมานิดนึง รบกวน recheck ครับ @thanisara-r

**Comment by thanisara-r** [comment]
ที่ข้อมูลไม่เหมือนกัน หายแล้วค่ะ แต่เว็บยังค้างๆ โหลดนานอยู่เลย
