### ISSUE TITLE
[Visual] Overview Chart ดูไม่ออกว่าเป็นชาร์ต

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#78]
เหมือนตอนนี้ scale มันไม่ตรงตามดีไซน์ไหมนะ?  + ตอนนี้เหมือนมันชิดขวา ทั้งที่ควร align ซ้าย (cc @monsichasri)
 
แล้วพอข้อมูลเล็กมาก ยิ่งดูเหมือนเว็บพังๆ
<img width="731" alt="image" src="https://user-images.githubusercontent.com/54769527/235663060-c04fb236-1869-47f5-b287-f97c2a0ef1db.png">

**Comment by monsichasri** [comment]
ไม่ตรงๆ น่าจะเป็น issue เดียวกับที่เรื่องขนาดที่เราเขียนไว้ แต่จอเราแสดงคนละแบบกัน

**Comment by Bariyard** [comment]
แก้เรื่องขนาดนิดนึงแล้วครับ please recheck @monsichasri

**Comment by monsichasri** [comment]
<img width="1440" alt="Screen Shot 2023-05-09 at 10 49 37" src="https://user-images.githubusercontent.com/132336578/236989320-7de3c1f9-8f20-4b21-a861-ab53880a0f80.png">
Scale ยังแปลกๆอยู่เลยค่ะ 
(chrome on macbook 13")

**Comment by Bariyard** [comment]
มันได้แค่นั้นจริงๆครับ เพราะ มันคือ scale ย่อ ของ chart ใหญ่

ซึ่ง data ทั้งหมด มี percentage ใกล้ 0 มาก

**Comment by monsichasri** [comment]
ถ้างั้นอย่างน้อยขอแถบ search ด้านบนแคบลงได้มั้ยคะใน desktop
![Screen Shot 2023-05-09 at 16 52 47](https://user-images.githubusercontent.com/132336578/237061712-f970d5ff-f77f-413f-9353-11eb5b970f71.png)

**Comment by thanisara-r** [comment]
ตัดส่วนนี้ออกได้เลยค่า
