### ISSUE TITLE
[Performance] กด sort มูลค่าหุ้น สูงสุด/ต่ำสุด แล้วโหลดนาน

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#79]
user อาจจะนึกว่าเว็บค้างได้ เข้าใจว่าข้อมูลเยอะ แต่พอจะ improve ได้ไหมนะ?

**Comment by Bariyard** [comment]
อันนี้ แก้ให้ของข้อมูลหลักเล็กลงนิดนึงแล้วครับ sort น่าจะเร็วขึ้นประมาน 2วิ
