### ISSUE TITLE
[Interaction] คนที่มีลิสต์บริษัทยาวๆ กด scroll แล้วมันไปทั้งหน้า

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#80]
https://user-images.githubusercontent.com/54769527/235666409-6368bd40-1f1d-4903-9f7f-30c1996ba4f7.mov

เข้าใจว่าต้อง scroll ตรง area ที่กำหนด แต่แอบยากสำหรับ user อยู่ พอจะล็อกหน้าไว้ได้ไหม?

**Comment by Bariyard** [comment]
แก้แล้วครับ
