### ISSUE TITLE
[Data] Wrong Data Display

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#81]
หน้าแรกขึ้นมูลค่าธุรกิจของ ส.ส. คนนี้ติดลบ
<img width="340" alt="image" src="https://user-images.githubusercontent.com/54769527/235668042-c32d3ae7-c3b2-4e71-95df-b91c90476e5d.png">

แต่กดดูข้อมูลแล้ว ก็ไม่ได้มีหุ้นในบริษัทไหน ดังนั้น ไม่ควรมีค่าข้อมูลมูลค่าธุรกิจสิ
<img width="533" alt="image" src="https://user-images.githubusercontent.com/54769527/235668331-fec2a2d4-3514-4173-9e39-380c4c8b7784.png">

แต่พอกดดูหน้า company view ปรากฎว่า
- มีข้อมูลขึ้นว่าเป็นผู้ถือหุ้น
- แต่มูลค่าบริษัท ก็ไม่ตรงกับตัวเลขหน้าแรกของ ส.ส.
<img width="465" alt="image" src="https://user-images.githubusercontent.com/54769527/235668783-8e7ca03f-326e-43fa-afe3-4bce72722468.png">

**Comment by Bariyard** [comment]
![image](https://user-images.githubusercontent.com/4732953/235850383-1e87ab31-bb27-4bac-bfb3-ca2477237d5f.png)
ผิดที่ ตัวเลข นับจำนวนบริษัทครับ ไม่ได้นับจำนวนบริษัทให้ถูกต้อง

**Comment by Bariyard** [comment]
done ka
