### ISSUE TITLE
[Visual] ชาร์ตพัง สำหรับบริษัทที่มีผู้ถือหุ้นรายย่อยมากๆ 

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#82]
ปรึกษา @monsichasri 

![image](https://user-images.githubusercontent.com/54769527/235669977-9828daad-5544-4571-b9bc-5f602e6b1d5c.png)
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/54769527/235670065-560fb259-4191-4ef8-aada-736e7df7b018.png">

(ลองกดดูตัวอย่างจากบริษัทในเครือข่ายของ ส.ว. ศิรินา ปวโรฬารวิทยา

**Comment by monsichasri** [comment]
ไม่แน่ใจว่ามันย่อให้ดูกระจายได้เล็กแค่ไหน เหมือนที่เราคุยกันตอนแรกว่าถ้ามันเยอะมากจะย่อลงจนมันไม่ชนกัน
แต่ในเคสนี้ถ้าย่อแล้วจะเล็กลงมากจนมองไม่เห็นมั้ยนะ อาจจะต้องลองดู

หรือเราสามารถรวบอื่นๆที่ไม่ใช่บุคคลได้มั้ย หรือไม่โชว์อันที่ไม่ใช่บุคคล 
แต่เหมือนพี่บาส @Bariyard บอกว่ามันไม่น่าแยกได้อาจจะยากเกินไปป

**Comment by Bariyard** [comment]
ยากเลยครับ กำลังลองวิทีย่อลงอยุ่ครับ

**Comment by Bariyard** [comment]
ตอนนี้แยกสลับสับหว่าง เป็น 2 วง ครับ ดูดีขึ้นมานิดนึงมั้ยนะ 
Please recheck @thanisara-r @monsichasri

**Comment by monsichasri** [comment]
![Screen Shot 2023-05-09 at 10 56 28](https://user-images.githubusercontent.com/132336578/236990328-f7e2790a-d9b8-48ec-b0d4-4eaec6c006a7.png)
ตรงบุคคลโอเคนะพอเป็น 2 ชั้น 
แต่พอเป็นบริษัทแล้วเยอะมากเราว่าแอบงงกว่าเดิม
เดี๋ยวลองหาวิธีอื่น

**Comment by thanisara-r** [comment]
viz ใน company view ให้แสดงเฉพาะ node ที่เป็นนักการเมือง
+ ขยาย text **ความเชื่อมโยงกับนักการเมือง** ให้ใหญ่ขึ้นได้นะ
(ลิสต์ฝั่งซ้ายคงไว้แบบเดิม)

**Comment by monsichasri** [comment]
คิดว่าต้องปรับตัวเลขฝั่งซ้ายที่บอกว่ามีนักการเมืองเกี่ยวข้องกี่คนให้เชื่อมโยงกับฝั่งขวาด้วย (อย่างในภาพนี้ควรเป็น 2 คน)
![Screen Shot 2023-05-10 at 10 34 28](https://github.com/wevisdemo/thailand-election-2023/assets/132336578/6408e3c0-ca12-4e5c-9d66-dd49cec88c25)

**Comment by Bariyard** [comment]
@monsichasri นั้นคือเลข 2 นะครับแพรวา ตัวมันเล็กไปมั้ยนะ @monsichasri

**Comment by thanisara-r** [comment]
<img width="484" alt="image" src="https://github.com/wevisdemo/thailand-election-2023/assets/54769527/68473d77-056b-40a1-9784-69ec96f31a01">

เหมือนมันเหลื่อมๆ ด้วยค่า ฝากลองปรับดู

**Comment by Bariyard** [comment]
done ka show only politician in chart
