### ISSUE TITLE
[Behavior] กดลูกศร ^ เพื่อส่องเพิ่มเติมยาก เพราะพื้นที่เล็ก น่าจะเพิ่ม clickable area เป็นทั้งแถบ

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#84]
![IMG_0877](https://user-images.githubusercontent.com/123941533/237004312-2c2872b3-78d2-4758-a49d-c3a0d12dadfe.PNG)

+ เขียนตกไม้เอก "สอง"เพิ่มเติม > "ส่อง"เพิ่มเติม

device : iphoneSE 3rd generation

**Comment by Bariyard** [comment]
done ka
