### ISSUE TITLE
[Data] ขึ้น undefined ในเคสที่เป็นกรรมการบริษัท

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#89]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/54769527/237012345-3903f78f-72dc-4413-8914-636769d00d35.png">

ไม่แน่ใจทำ design ไว้รองรับเคสที่เป็นกรรมการบริษัทไว้ไหม @monsichasri 
- สัดส่วนหุ้น ควรแสดงปกติไหมนะ?
- เพียงแต่ตอนโยง อาจจะขึ้นว่าเป็นกรรมการไหม? (ตอนนี้ขึ้น undefined)

**Comment by monsichasri** [comment]
ตรง undefined ควรขึ้นเป็นชื่อคนนะ 
เป็นกรรมการคือมีเส้นโยงแต่ไม่มีชื่อในหุ้นเฉยๆ ตอนนี้ไม่ได้ทำลิสต์แยกไว้
