### ISSUE TITLE
[Visual] text ถูกตัดบรรทัดแม้จะมีที่เหลือ

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/thailand-election-2023#9]
browser : Safari (chromeไม่เป็น)
![CleanShot 2566-04-04 at 13 23 43](https://user-images.githubusercontent.com/123941533/229705651-cbdf91e0-0fb4-4505-80da-20c3a7af8025.png)

+ อยากให้ text align left ไม่ใช่ center
![CleanShot 2566-04-04 at 13 27 02@2x](https://user-images.githubusercontent.com/123941533/229706328-ed52f3c6-3c38-40dc-8c11-447095ae9647.png)

**Comment by napatswift** [comment]
done kub
