### ISSUE TITLE
[Visual] ลำดับ filter หมวดธุรกิจ

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#90]
filter ขอให้**ทุกหมวดธุรกิจ**อยู่บนสุดตลอดได้มั้ยคะ ที่เหลือลำดับตามนี้โอเคแล้ว
<img width="763" alt="Screen Shot 2023-05-10 at 10 25 20" src="https://github.com/wevisdemo/thailand-election-2023/assets/132336578/508db82a-8d79-45dd-8faa-d48491e0c24c">

**Comment by Bariyard** [comment]
done ka
