### ISSUE TITLE
[Visual][Low priority] filter พรรค สว มี icon ของตัวเองแต่ สส. ครม. ไม่มี

### ISSUE THREAD

**Issue by monsichasri** [wevisdemo/thailand-election-2023#91]
ถ้าเป็นไปได้อยากให้มันเหมือนกันค่ะ ให้มี สส กับ ครม ขึ้นเป็น รูปเหมือน สว. < ต้องทำเพิ่มให้มั้ย เข้าใจว่าที่ดึงมาจาก noco ไม่มี
หรือถ้าไม่มีก็ไม่มีเหมือนกันไปเลยค่ะ
<img width="763" alt="Screen Shot 2023-05-10 at 10 26 40" src="https://github.com/wevisdemo/thailand-election-2023/assets/132336578/492afa8d-ac2f-4c96-91df-9effa989aa21">

**Comment by Bariyard** [comment]
@monsichasri สามารถเอารูปไปใส่ใน nocodb ได้เลยนะครับ จะอัพเดทบนเว็บได้เลย

**Comment by monsichasri** [comment]
เราไม่มี access ในการเพิ่มรูปงะ ถ้าว่างๆ ฝากใส่หรือเปิด accessให้หน่อยค่า [](https://drive.google.com/drive/folders/1rVS0eGKdEBe_8IrIMxl-bUjIYDiO6ryE)

**Comment by Bariyard** [comment]
done ka
