### ISSUE TITLE
[Text] Tutorial ปุ่มสอง ตกคำว่า ธุรกิจ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#92]
![image](https://github.com/wevisdemo/thailand-election-2023/assets/54769527/1bbdc6fa-edf7-4670-ab3b-94493ed45f8f)

ธุรกิจที่เกี่ยวกับนักการเมืองแบบไหน
รับเงินจากโครงการรัฐเยอะ?

**Comment by Bariyard** [comment]
done ka
