### ISSUE TITLE
[Data] ผู้สมัคร บัญชีรายชื่อ 66 ในชาร์ตมันขึ้นว่าอยู่พรรคไหน แต่ในหน้าบุคคลขึ้นว่าไม่มีสังกัดหมดเลย

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#93]
ผู้สมัคร บัญชีรายชื่อ ในชาร์ตมันขึ้นว่าอยู่พรรคไหน แต่ในหน้าบุคคลขึ้นว่าไม่มีสังกัดหมดเลยอะ
![image](https://github.com/wevisdemo/thailand-election-2023/assets/54769527/a58e9ede-365c-4a8e-b698-425225f61af1)
![image](https://github.com/wevisdemo/thailand-election-2023/assets/54769527/46368b6e-0b08-471a-bfe4-060831931fe6)
![image](https://github.com/wevisdemo/thailand-election-2023/assets/54769527/5e53d746-746b-4bc2-9d8c-3b558b27bad2)

**Comment by Bariyard** [comment]
fixed ka
