### ISSUE TITLE
[Data] ช่วยเรียงบริษัทที่บุคคลถือหุ้นตามสัดส่วนหุ้น มาก > น้อย หน่อยค่ะ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#94]
<img width="499" alt="image" src="https://github.com/wevisdemo/thailand-election-2023/assets/54769527/8bfde909-fca0-499f-9777-ee35006e3d4b">

**Comment by Th1nkK1D** [comment]
Implemented in 97a21531d64b71a4add6ab8188f011c5eafea5d2
