### ISSUE TITLE
[Text] ปรับเพิ่ม text หน้าแรกค่ะ

### ISSUE THREAD

**Issue by thanisara-r** [wevisdemo/thailand-election-2023#95]
<img width="499" alt="image" src="https://github.com/wevisdemo/thailand-election-2023/assets/54769527/d9ea4c92-5df9-4de5-b245-cc7c4113c482">

อดีต ส.ส. และ ครม. รวมถึง ส.ว. จากการเลือกตั้ง 62

**Comment by rootEnginear** [comment]
รับงานค่ะ

**Comment by rootEnginear** [comment]
Forward to @Bariyard เนื่องจากไม่แน่ใจว่าต้อง implement อะไรเพิ่มเพื่อขึ้น text ที่ต้องการไหม
https://github.com/wevisdemo/thailand-election-2023/blob/f6a8fc97298d44b6549d7709b575ee2c363ee7bf/apps/mpasset/src/components/section3/second-chart/PersonDetail.tsx#L110-L116

**Comment by Bariyard** [comment]
@thanisara-r สรุปอันนี้คือจะรวม dataset เป็นชุดเดียว หรือ เอา ของ 62 มาใส้ใน 66 ด้วยครับ

**Comment by Bariyard** [comment]
ถ้าจะโชว์ใน set66 อาจจะต้องแก้ที่ data ครับ @thanisara-r

**Comment by Bariyard** [comment]
![image](https://github.com/wevisdemo/thailand-election-2023/assets/4732953/9a1df53f-1b24-4537-94a4-4745e568bda1)

อวยยศให้แล้วค่า @thanisara-r
