### ISSUE TITLE
[Data] Chart ใช้ totalPctShare แต่ label ใช้ totalValueShare

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/thailand-election-2023#99]
คิดว่าอันนี้ critical นิดนึงครับ ผมพบว่าจาก code ตอนนี้ขนาดของ barchart ถูกคำนวนจาก `totalPctShare` (MainNav.tsx line 183) แต่ว่า label ที่แสดงคู่กันกันแสดงจาก `totalValueShare` (MainNav.tsx line 202)

![image](https://github.com/wevisdemo/thailand-election-2023/assets/8860448/9530b0cb-8adb-4ffa-8350-10c110c7c45b)

ซึ่งอันนี้ทำให้ label กับ barchart ไม่สอดคล้องกัน ที่เห็นได้ชัดก็คือจุดที่ label (`totalValueShare`) ระบุว่าเป็นลบ แต่ว่า chart บางส่วนแสดงด้านบวก บางส่วนแสดงด้านลบ

![image](https://github.com/wevisdemo/thailand-election-2023/assets/8860448/60246481-ca4e-4e1a-ab9b-01bc3f564ead)

ผมยังไม่ได้แก้เพราะว่าไม่รู้ว่าที่ถูกต้องเราต้องเลือกใช้ค่า `totalPctShare` หรือ `totalValueShare` ครับ @Bariyard @thanisara-r

**Comment by Th1nkK1D** [comment]
สืบเนื่องจาก issue ข้างบน sorting ของคนตอนนี้ถ้าอิงจาก label `totalValueShare` มันดูมั่วๆ ตามนี้

1. positive
2. "เกี่ยวข้องกับธุรกิจแต่ไม่มีหุ้นอยู่"
3. negative
4. "เกี่ยวข้องกับธุรกิจแต่ไม่มีหุ้นอยู่" (อีกก้อน ดูภายนอกเหมือนข้างบนเด้ะ แต่ทำไมถึงมาอยู่ตรงนี้ได้)
5. "ไม่เกี่ยวข้องกับธุรกิจ" (สรุปอันนี้ยังแสดงอยู่เหรอ เหมือนเคยคุยว่าจะเอาออกเพราะกดเข้าไปก็ไม่มีข้อมูลอะไร)

ถ้า issue บนเลือกได้แล้วว่าจะใช้ค่าไหน คิดว่าแก้ได้ไม่นานและควรทำครับ

**Comment by Th1nkK1D** [comment]
สรุป
- barchart ถูกคำนวนจาก totalPctShare และ label จาก totalValueShare ถูกแล้ว
- แก้ logic การ flip ให้ใช้ totalValueShare แล้ว 4544d91b849c58de9d1b8689b83d14adb4b62c62
- เพิ่ม gradient ที่ outlier ให้รู้ว่ามันยาวกว่านี้แต่เราแสดงไม่หมด 838fb9ca0ab2668a51cd7e3ef0e6a594023265b2
![image](https://github.com/wevisdemo/thailand-election-2023/assets/8860448/f67294b9-b59c-4420-b3b3-d11dafc7e2e2)

ฝาก @Bariyard recheck sorting logic แล้วปิด issue นี้ได้เลยครับ

**Comment by Bariyard** [comment]
fixed เรื่อง sorting แล้วครับ @Th1nkK1D
